// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "github.com/go-park-mail-ru/2020_2_Slash/internal/helpers/errors"
	models "github.com/go-park-mail-ru/2020_2_Slash/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSessionUsecase is a mock of SessionUsecase interface
type MockSessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSessionUsecaseMockRecorder
}

// MockSessionUsecaseMockRecorder is the mock recorder for MockSessionUsecase
type MockSessionUsecaseMockRecorder struct {
	mock *MockSessionUsecase
}

// NewMockSessionUsecase creates a new mock instance
func NewMockSessionUsecase(ctrl *gomock.Controller) *MockSessionUsecase {
	mock := &MockSessionUsecase{ctrl: ctrl}
	mock.recorder = &MockSessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSessionUsecase) EXPECT() *MockSessionUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockSessionUsecase) Create(sess *models.Session) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", sess)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockSessionUsecaseMockRecorder) Create(sess interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionUsecase)(nil).Create), sess)
}

// Get mocks base method
func (m *MockSessionUsecase) Get(sessValue string) (*models.Session, *errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", sessValue)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(*errors.Error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockSessionUsecaseMockRecorder) Get(sessValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionUsecase)(nil).Get), sessValue)
}

// Delete mocks base method
func (m *MockSessionUsecase) Delete(sessionValue string) *errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", sessionValue)
	ret0, _ := ret[0].(*errors.Error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockSessionUsecaseMockRecorder) Delete(sessionValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionUsecase)(nil).Delete), sessionValue)
}

// Check mocks base method
func (m *MockSessionUsecase) Check(sessValue string) (*models.Session, *errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", sessValue)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(*errors.Error)
	return ret0, ret1
}

// Check indicates an expected call of Check
func (mr *MockSessionUsecaseMockRecorder) Check(sessValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSessionUsecase)(nil).Check), sessValue)
}
